.gitignore, .vscode/extensions.json, .vscode/launch.json, .vscode/settings.json, README.md, _tasks/dnt.ts
Resolves #
- Links for support channels
* Add link to stackgexchange in readme
* * Add link to Element chat in readme
=> chore: add support channels to readme

_tasks/dnt.ts
Resolves #
- Duplicate React instances
=> feat: set react as peerDependency

core/hooks/contracts/useCall.ts, core/hooks/contracts/useDryRun.ts, core/hooks/contracts/useTx.ts, core/hooks/contracts/useTxPaymentInfo.ts, core/hooks/mod.ts, core/hooks/useWallet.ts, core/hooks/wallets/mod.ts, core/hooks/wallets/useInstalledWallets.ts, core/hooks/wallets/useUninstalledWallets.ts, core/hooks/wallets/useWallet.ts, core/providers/wallet/model.ts, notifications/hooks/useTxNotifications.ts
Resolves #
I'm working on the documentation website and realized how helpful this would be for the docs. Making a quick PR...
=> feat: add wallet hooks

core/providers/wallet/model.ts, core/providers/wallet/provider.tsx
Resolves #
Add a boolean for wallet connection state
=> feat: add isConnected to WalletState

core/hooks/wallets/mod.ts, core/hooks/wallets/useAllWallets.ts
Resolves #
Add `useAllWallets`, which is a hook wrapper around `getWallets()`
=> feat: add useAllWallets

README.md
=> chore: style readme

core/types/contracts.ts, core/utils/contracts/decodeError.ts, utils/mod.ts, utils/pickCallInfo.ts, utils/pickTxInfo.ts
Resolves #
Add more `pick*` helpers
=> feat: add more pick* helpers

react/hooks/contracts/useDryRun.ts
=> fix: destructure useDryRun args in send()

react/providers/wallet/provider.tsx
Resolves #
We now check localStorage for autoconnect wallet info inside of `useEffect`, which only fires after document is ready. This fixes the bug where Polkadot Wallet was not auto connecting half of the time as mentioned [here](https://github.com/paritytech/link/issues/265).
=> fix: auto wallet connect

react/hooks/contracts/useEvents.ts
=> fix: useEvents arg types

core/contracts/mod.ts, core/contracts/txPaymentInfo.ts, react/hooks/contracts/useEvents.ts, react/hooks/contracts/useTxPaymentInfo.ts, utils/mod.ts, utils/substrate/bnToBalance.ts, utils/substrate/mod.ts
Resolves #
* Add `bnToBalance` helper function
* Add `txPaymentInfo` to `useink/core` to fetch gas info for a message
=> feat: add helper and core functions

core/substrate/balances/mod.ts, core/substrate/balances/transfer.ts, core/types/substrate.ts, react/hooks/substrate/mod.ts, react/hooks/substrate/useTransfer.ts
Resolves #
* Add `transfer` in `useink/core`
* Add `useTransfer` in `useink`
=> feat: add transfer and useTransfer

packages/useink/package.json, pnpm-lock.yaml
=> chore: update package version

packages/useink/package.json, packages/useink/src/core/types/contracts.ts, playground/src/components/pg-home/HomePage.tsx, pnpm-lock.yaml
=> chore: add api-contract dep

package.json
=> chore: add README to package dist

packages/useink/package.json, packages/useink/src/utils/helpers/parseUnits/parseUnits.ts
=> feat: allow planck* helpers to receive undefined api val

packages/useink/package.json, packages/useink/src/core/substrate/timestamp/getTimestamp.ts, packages/useink/src/core/substrate/timestamp/getTimestampDate.ts, packages/useink/src/core/substrate/timestamp/getTimestampNow.ts, packages/useink/src/core/substrate/timestamp/getTimestampQuery.ts, packages/useink/src/core/substrate/timestamp/index.ts, packages/useink/src/react/hooks/helpers/index.ts, packages/useink/src/react/hooks/helpers/useUnixMilliToDate.ts, packages/useink/src/react/hooks/index.ts, packages/useink/src/react/hooks/substrate/balance/index.ts, packages/useink/src/react/hooks/substrate/balance/useBalance.ts, packages/useink/src/react/hooks/substrate/index.ts, packages/useink/src/react/hooks/substrate/timestamp/index.ts, packages/useink/src/react/hooks/substrate/timestamp/useTimestampDate.ts, packages/useink/src/react/hooks/substrate/timestamp/useTimestampNow.ts, packages/useink/src/react/hooks/substrate/timestamp/useTimestampQuery.ts, packages/useink/src/utils/helpers/index.ts, packages/useink/src/utils/helpers/unixMilliToDate.ts, playground/src/components/pg-home/HomePage.tsx, words.txt
Resolves #
Add timestamp hooks and helpers
=> feat: add timestamp hooks and core funcs

packages/useink/src/react/hooks/contracts/useDeployer/types.ts, packages/useink/src/react/hooks/contracts/useDeployer/useDeployer.ts
=> feat: add field to useDeployer

packages/useink/src/react/hooks/contracts/useDeployer/useDeployer.ts, packages/useink/src/utils/contracts/toMessageParams.ts, packages/useink/src/utils/helpers/NOOP.ts, playground/src/components/pg-deploy/DeployPage.tsx
Resolves #
Fix bug in `useDeployer().dryRun()` where encoded message params were passed incorrectly.
=> fix: useDeployer

packages/useink/src/core/types/talisman-connect-wallets.ts
=> fix: wallet account type

.github/workflows/lint.yml, .github/workflows/release.yml, biome.json, package.json, packages/useink/package.json, packages/useink/src/core/types/api-contract.ts, packages/useink/src/core/types/talisman-connect-wallets.ts, packages/useink/src/react/hooks/contracts/useDeployer/types.ts, packages/useink/src/react/hooks/contracts/useTx.ts, playground/src/components/pg-home/HomePage.tsx, pnpm-lock.yaml
Resolves #105
Resolved in the underlying pjs library, thereby a bump of this dependency will fix the issue for all `useink` users.
=> fix: 105 not correct decoding of i16 edge values
